name: Database Migration and Seeding

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  migrate-and-seed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Drizzle types
      run: npx drizzle-kit generate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Run database migrations
      run: npm run db:push
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Seed database
      run: node scripts/seed-standalone.js
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Verify build still works
      run: npm run build
      env:
        NODE_ENV: production